// Code generated by Thrift Compiler (0.17.0). DO NOT EDIT.

package tradingservice

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/thrasher-corp/gocryptotrader/market-maker/trading-service/types"
	// "types"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = types.GoUnusedProtection__

func init() {
}

