// Code generated by Thrift Compiler (0.17.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"types"
	"tradingservice"
)

var _ = types.GoUnusedProtection__
var _ = tradingservice.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i32 getTradeDate()")
  fmt.Fprintln(os.Stderr, "  i64 getServerTime()")
  fmt.Fprintln(os.Stderr, "  i32 getServerTimeZone()")
  fmt.Fprintln(os.Stderr, "  void delBlob(string key)")
  fmt.Fprintln(os.Stderr, "  string getBlob(string key)")
  fmt.Fprintln(os.Stderr, "  void setBlob(string key, string blob)")
  fmt.Fprintln(os.Stderr, "  Session login(string user, string password, string platform, string ipAddr, i32 port)")
  fmt.Fprintln(os.Stderr, "  i32 touchSession(string sessionID)")
  fmt.Fprintln(os.Stderr, "  i32 logout(string sessionID)")
  fmt.Fprintln(os.Stderr, "  i32 placeOrder(Order order)")
  fmt.Fprintln(os.Stderr, "  i32 amendOrder(Order order)")
  fmt.Fprintln(os.Stderr, "  i32 cancelOrder(Order order)")
  fmt.Fprintln(os.Stderr, "  i32 registerBlockTrade(BlockTrade trade)")
  fmt.Fprintln(os.Stderr, "   getExchanges()")
  fmt.Fprintln(os.Stderr, "   getCurrencies()")
  fmt.Fprintln(os.Stderr, "  Instrument getInstrument(i32 instrumentID)")
  fmt.Fprintln(os.Stderr, "   getMyWatchList(string user)")
  fmt.Fprintln(os.Stderr, "   getInstruments(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getInstrumentGroups(string user)")
  fmt.Fprintln(os.Stderr, "   getInstrumentByGroup(string group)")
  fmt.Fprintln(os.Stderr, "  bool addToMyWatchList(string user, i32 instrumentID)")
  fmt.Fprintln(os.Stderr, "  bool removeFromMyWatchList(string user, i32 instrumentID)")
  fmt.Fprintln(os.Stderr, "  Quote getQuote(i32 instrumentID)")
  fmt.Fprintln(os.Stderr, "   getMyQuotes(string user)")
  fmt.Fprintln(os.Stderr, "   getQuotes( items)")
  fmt.Fprintln(os.Stderr, "   getQuoteList(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getQuoteMap( items)")
  fmt.Fprintln(os.Stderr, "  Bars getNBars(i32 instrumentID, BarInterval interval, i32 noOfBars)")
  fmt.Fprintln(os.Stderr, "  Bars getBarsSince(i32 instrumentID, BarInterval interval, i64 since)")
  fmt.Fprintln(os.Stderr, "   getNews(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "  Order getOrder(i32 orderID)")
  fmt.Fprintln(os.Stderr, "   getFills(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getOrders(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getOrderHistory(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "  Account getAccount(i32 accountID)")
  fmt.Fprintln(os.Stderr, "  Account getDefaultAccount(string user)")
  fmt.Fprintln(os.Stderr, "  AccountProfile getAccountProfile(string account)")
  fmt.Fprintln(os.Stderr, "  void setAccountProfile(AccountProfile accountProfile)")
  fmt.Fprintln(os.Stderr, "   getAccounts(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getPositions(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getChildPositions(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getFinTransTypes()")
  fmt.Fprintln(os.Stderr, "   getFinTrans(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "   getDailyLedger(SearchCriteria criteria)")
  fmt.Fprintln(os.Stderr, "  bool isPasswordChangeRequred(string user)")
  fmt.Fprintln(os.Stderr, "  bool changePassword(string user, string oldPassword, string newPassword)")
  fmt.Fprintln(os.Stderr, "   getSettings(string user)")
  fmt.Fprintln(os.Stderr, "  string getSetting(string user, string key)")
  fmt.Fprintln(os.Stderr, "  bool delSetting(string user, string key)")
  fmt.Fprintln(os.Stderr, "  bool saveSetting(string user, string key, string value)")
  fmt.Fprintln(os.Stderr, "  bool isUserRegistered(string username)")
  fmt.Fprintln(os.Stderr, "  void sendMail(string email, string subject, string content)")
  fmt.Fprintln(os.Stderr, "  void sendMailEx(string recipient, string subject, string mail,  attachments)")
  fmt.Fprintln(os.Stderr, "  Account registerAccount(string username, string password, string broker, string referrer)")
  fmt.Fprintln(os.Stderr, "  void requestWithdraw(string account, string ccy, double amount)")
  fmt.Fprintln(os.Stderr, "   getAccountAttributes(string account)")
  fmt.Fprintln(os.Stderr, "  void delAccountAttribute(string account, string group, string key)")
  fmt.Fprintln(os.Stderr, "  string getAccountAttribute(string account, string group, string key)")
  fmt.Fprintln(os.Stderr, "  void setAccountAttribute(string account, string tag, string group, string value)")
  fmt.Fprintln(os.Stderr, "  void setUser(User user)")
  fmt.Fprintln(os.Stderr, "  void setQuote(Quote quote)")
  fmt.Fprintln(os.Stderr, "  void setRating(Rating rate)")
  fmt.Fprintln(os.Stderr, "  void delRating(Rating rate)")
  fmt.Fprintln(os.Stderr, "  void setAccount(Account account)")
  fmt.Fprintln(os.Stderr, "  void setSettlementPrice(SettlementPrice price)")
  fmt.Fprintln(os.Stderr, "  void setUserSession(UserSession userSession)")
  fmt.Fprintln(os.Stderr, "  void archiveUserSession(UserSession userSession)")
  fmt.Fprintln(os.Stderr, "  void setAccountLimit(AccountLimit limit)")
  fmt.Fprintln(os.Stderr, "  void delAccountLimit(string account, string product, string instrument)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := tradingservice.NewTradingServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "getTradeDate":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetTradeDate requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetTradeDate(context.Background()))
    fmt.Print("\n")
    break
  case "getServerTime":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetServerTime requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetServerTime(context.Background()))
    fmt.Print("\n")
    break
  case "getServerTimeZone":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetServerTimeZone requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetServerTimeZone(context.Background()))
    fmt.Print("\n")
    break
  case "delBlob":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DelBlob requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.DelBlob(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getBlob":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetBlob requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetBlob(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setBlob":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SetBlob requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SetBlob(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "login":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "Login requires 5 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    tmp4, err392 := (strconv.Atoi(flag.Arg(5)))
    if err392 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    fmt.Print(client.Login(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "touchSession":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "TouchSession requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.TouchSession(context.Background(), value0))
    fmt.Print("\n")
    break
  case "logout":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Logout requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Logout(context.Background(), value0))
    fmt.Print("\n")
    break
  case "placeOrder":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "PlaceOrder requires 1 args")
      flag.Usage()
    }
    arg395 := flag.Arg(1)
    mbTrans396 := thrift.NewTMemoryBufferLen(len(arg395))
    defer mbTrans396.Close()
    _, err397 := mbTrans396.WriteString(arg395)
    if err397 != nil {
      Usage()
      return
    }
    factory398 := thrift.NewTJSONProtocolFactory()
    jsProt399 := factory398.GetProtocol(mbTrans396)
    argvalue0 := types.NewOrder()
    err400 := argvalue0.Read(context.Background(), jsProt399)
    if err400 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.PlaceOrder(context.Background(), value0))
    fmt.Print("\n")
    break
  case "amendOrder":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AmendOrder requires 1 args")
      flag.Usage()
    }
    arg401 := flag.Arg(1)
    mbTrans402 := thrift.NewTMemoryBufferLen(len(arg401))
    defer mbTrans402.Close()
    _, err403 := mbTrans402.WriteString(arg401)
    if err403 != nil {
      Usage()
      return
    }
    factory404 := thrift.NewTJSONProtocolFactory()
    jsProt405 := factory404.GetProtocol(mbTrans402)
    argvalue0 := types.NewOrder()
    err406 := argvalue0.Read(context.Background(), jsProt405)
    if err406 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.AmendOrder(context.Background(), value0))
    fmt.Print("\n")
    break
  case "cancelOrder":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CancelOrder requires 1 args")
      flag.Usage()
    }
    arg407 := flag.Arg(1)
    mbTrans408 := thrift.NewTMemoryBufferLen(len(arg407))
    defer mbTrans408.Close()
    _, err409 := mbTrans408.WriteString(arg407)
    if err409 != nil {
      Usage()
      return
    }
    factory410 := thrift.NewTJSONProtocolFactory()
    jsProt411 := factory410.GetProtocol(mbTrans408)
    argvalue0 := types.NewOrder()
    err412 := argvalue0.Read(context.Background(), jsProt411)
    if err412 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.CancelOrder(context.Background(), value0))
    fmt.Print("\n")
    break
  case "registerBlockTrade":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RegisterBlockTrade requires 1 args")
      flag.Usage()
    }
    arg413 := flag.Arg(1)
    mbTrans414 := thrift.NewTMemoryBufferLen(len(arg413))
    defer mbTrans414.Close()
    _, err415 := mbTrans414.WriteString(arg413)
    if err415 != nil {
      Usage()
      return
    }
    factory416 := thrift.NewTJSONProtocolFactory()
    jsProt417 := factory416.GetProtocol(mbTrans414)
    argvalue0 := types.NewBlockTrade()
    err418 := argvalue0.Read(context.Background(), jsProt417)
    if err418 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.RegisterBlockTrade(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getExchanges":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetExchanges requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetExchanges(context.Background()))
    fmt.Print("\n")
    break
  case "getCurrencies":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetCurrencies requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetCurrencies(context.Background()))
    fmt.Print("\n")
    break
  case "getInstrument":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetInstrument requires 1 args")
      flag.Usage()
    }
    tmp0, err419 := (strconv.Atoi(flag.Arg(1)))
    if err419 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetInstrument(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getMyWatchList":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetMyWatchList requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetMyWatchList(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getInstruments":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetInstruments requires 1 args")
      flag.Usage()
    }
    arg421 := flag.Arg(1)
    mbTrans422 := thrift.NewTMemoryBufferLen(len(arg421))
    defer mbTrans422.Close()
    _, err423 := mbTrans422.WriteString(arg421)
    if err423 != nil {
      Usage()
      return
    }
    factory424 := thrift.NewTJSONProtocolFactory()
    jsProt425 := factory424.GetProtocol(mbTrans422)
    argvalue0 := types.NewSearchCriteria()
    err426 := argvalue0.Read(context.Background(), jsProt425)
    if err426 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetInstruments(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getInstrumentGroups":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetInstrumentGroups requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetInstrumentGroups(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getInstrumentByGroup":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetInstrumentByGroup requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetInstrumentByGroup(context.Background(), value0))
    fmt.Print("\n")
    break
  case "addToMyWatchList":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AddToMyWatchList requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err430 := (strconv.Atoi(flag.Arg(2)))
    if err430 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.AddToMyWatchList(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "removeFromMyWatchList":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RemoveFromMyWatchList requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err432 := (strconv.Atoi(flag.Arg(2)))
    if err432 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.RemoveFromMyWatchList(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getQuote":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetQuote requires 1 args")
      flag.Usage()
    }
    tmp0, err433 := (strconv.Atoi(flag.Arg(1)))
    if err433 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetQuote(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getMyQuotes":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetMyQuotes requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetMyQuotes(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getQuotes":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetQuotes requires 1 args")
      flag.Usage()
    }
    arg435 := flag.Arg(1)
    mbTrans436 := thrift.NewTMemoryBufferLen(len(arg435))
    defer mbTrans436.Close()
    _, err437 := mbTrans436.WriteString(arg435)
    if err437 != nil { 
      Usage()
      return
    }
    factory438 := thrift.NewTJSONProtocolFactory()
    jsProt439 := factory438.GetProtocol(mbTrans436)
    containerStruct0 := tradingservice.NewTradingServiceGetQuotesArgs()
    err440 := containerStruct0.ReadField1(context.Background(), jsProt439)
    if err440 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Items
    value0 := argvalue0
    fmt.Print(client.GetQuotes(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getQuoteList":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetQuoteList requires 1 args")
      flag.Usage()
    }
    arg441 := flag.Arg(1)
    mbTrans442 := thrift.NewTMemoryBufferLen(len(arg441))
    defer mbTrans442.Close()
    _, err443 := mbTrans442.WriteString(arg441)
    if err443 != nil {
      Usage()
      return
    }
    factory444 := thrift.NewTJSONProtocolFactory()
    jsProt445 := factory444.GetProtocol(mbTrans442)
    argvalue0 := types.NewSearchCriteria()
    err446 := argvalue0.Read(context.Background(), jsProt445)
    if err446 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetQuoteList(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getQuoteMap":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetQuoteMap requires 1 args")
      flag.Usage()
    }
    arg447 := flag.Arg(1)
    mbTrans448 := thrift.NewTMemoryBufferLen(len(arg447))
    defer mbTrans448.Close()
    _, err449 := mbTrans448.WriteString(arg447)
    if err449 != nil { 
      Usage()
      return
    }
    factory450 := thrift.NewTJSONProtocolFactory()
    jsProt451 := factory450.GetProtocol(mbTrans448)
    containerStruct0 := tradingservice.NewTradingServiceGetQuoteMapArgs()
    err452 := containerStruct0.ReadField1(context.Background(), jsProt451)
    if err452 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Items
    value0 := argvalue0
    fmt.Print(client.GetQuoteMap(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getNBars":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetNBars requires 3 args")
      flag.Usage()
    }
    tmp0, err453 := (strconv.Atoi(flag.Arg(1)))
    if err453 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := tradingservice.BarInterval(tmp1)
    value1 := argvalue1
    tmp2, err454 := (strconv.Atoi(flag.Arg(3)))
    if err454 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetNBars(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getBarsSince":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetBarsSince requires 3 args")
      flag.Usage()
    }
    tmp0, err455 := (strconv.Atoi(flag.Arg(1)))
    if err455 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := tradingservice.BarInterval(tmp1)
    value1 := argvalue1
    argvalue2, err456 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err456 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    fmt.Print(client.GetBarsSince(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getNews":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetNews requires 1 args")
      flag.Usage()
    }
    arg457 := flag.Arg(1)
    mbTrans458 := thrift.NewTMemoryBufferLen(len(arg457))
    defer mbTrans458.Close()
    _, err459 := mbTrans458.WriteString(arg457)
    if err459 != nil {
      Usage()
      return
    }
    factory460 := thrift.NewTJSONProtocolFactory()
    jsProt461 := factory460.GetProtocol(mbTrans458)
    argvalue0 := types.NewSearchCriteria()
    err462 := argvalue0.Read(context.Background(), jsProt461)
    if err462 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetNews(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getOrder":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetOrder requires 1 args")
      flag.Usage()
    }
    tmp0, err463 := (strconv.Atoi(flag.Arg(1)))
    if err463 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetOrder(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getFills":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetFills requires 1 args")
      flag.Usage()
    }
    arg464 := flag.Arg(1)
    mbTrans465 := thrift.NewTMemoryBufferLen(len(arg464))
    defer mbTrans465.Close()
    _, err466 := mbTrans465.WriteString(arg464)
    if err466 != nil {
      Usage()
      return
    }
    factory467 := thrift.NewTJSONProtocolFactory()
    jsProt468 := factory467.GetProtocol(mbTrans465)
    argvalue0 := types.NewSearchCriteria()
    err469 := argvalue0.Read(context.Background(), jsProt468)
    if err469 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetFills(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getOrders":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetOrders requires 1 args")
      flag.Usage()
    }
    arg470 := flag.Arg(1)
    mbTrans471 := thrift.NewTMemoryBufferLen(len(arg470))
    defer mbTrans471.Close()
    _, err472 := mbTrans471.WriteString(arg470)
    if err472 != nil {
      Usage()
      return
    }
    factory473 := thrift.NewTJSONProtocolFactory()
    jsProt474 := factory473.GetProtocol(mbTrans471)
    argvalue0 := types.NewSearchCriteria()
    err475 := argvalue0.Read(context.Background(), jsProt474)
    if err475 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetOrders(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getOrderHistory":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetOrderHistory requires 1 args")
      flag.Usage()
    }
    arg476 := flag.Arg(1)
    mbTrans477 := thrift.NewTMemoryBufferLen(len(arg476))
    defer mbTrans477.Close()
    _, err478 := mbTrans477.WriteString(arg476)
    if err478 != nil {
      Usage()
      return
    }
    factory479 := thrift.NewTJSONProtocolFactory()
    jsProt480 := factory479.GetProtocol(mbTrans477)
    argvalue0 := types.NewSearchCriteria()
    err481 := argvalue0.Read(context.Background(), jsProt480)
    if err481 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetOrderHistory(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getAccount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetAccount requires 1 args")
      flag.Usage()
    }
    tmp0, err482 := (strconv.Atoi(flag.Arg(1)))
    if err482 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetAccount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getDefaultAccount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDefaultAccount requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetDefaultAccount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getAccountProfile":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetAccountProfile requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetAccountProfile(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setAccountProfile":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetAccountProfile requires 1 args")
      flag.Usage()
    }
    arg485 := flag.Arg(1)
    mbTrans486 := thrift.NewTMemoryBufferLen(len(arg485))
    defer mbTrans486.Close()
    _, err487 := mbTrans486.WriteString(arg485)
    if err487 != nil {
      Usage()
      return
    }
    factory488 := thrift.NewTJSONProtocolFactory()
    jsProt489 := factory488.GetProtocol(mbTrans486)
    argvalue0 := types.NewAccountProfile()
    err490 := argvalue0.Read(context.Background(), jsProt489)
    if err490 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetAccountProfile(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getAccounts":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetAccounts requires 1 args")
      flag.Usage()
    }
    arg491 := flag.Arg(1)
    mbTrans492 := thrift.NewTMemoryBufferLen(len(arg491))
    defer mbTrans492.Close()
    _, err493 := mbTrans492.WriteString(arg491)
    if err493 != nil {
      Usage()
      return
    }
    factory494 := thrift.NewTJSONProtocolFactory()
    jsProt495 := factory494.GetProtocol(mbTrans492)
    argvalue0 := types.NewSearchCriteria()
    err496 := argvalue0.Read(context.Background(), jsProt495)
    if err496 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetAccounts(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getPositions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPositions requires 1 args")
      flag.Usage()
    }
    arg497 := flag.Arg(1)
    mbTrans498 := thrift.NewTMemoryBufferLen(len(arg497))
    defer mbTrans498.Close()
    _, err499 := mbTrans498.WriteString(arg497)
    if err499 != nil {
      Usage()
      return
    }
    factory500 := thrift.NewTJSONProtocolFactory()
    jsProt501 := factory500.GetProtocol(mbTrans498)
    argvalue0 := types.NewSearchCriteria()
    err502 := argvalue0.Read(context.Background(), jsProt501)
    if err502 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetPositions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getChildPositions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetChildPositions requires 1 args")
      flag.Usage()
    }
    arg503 := flag.Arg(1)
    mbTrans504 := thrift.NewTMemoryBufferLen(len(arg503))
    defer mbTrans504.Close()
    _, err505 := mbTrans504.WriteString(arg503)
    if err505 != nil {
      Usage()
      return
    }
    factory506 := thrift.NewTJSONProtocolFactory()
    jsProt507 := factory506.GetProtocol(mbTrans504)
    argvalue0 := types.NewSearchCriteria()
    err508 := argvalue0.Read(context.Background(), jsProt507)
    if err508 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetChildPositions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getFinTransTypes":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetFinTransTypes requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetFinTransTypes(context.Background()))
    fmt.Print("\n")
    break
  case "getFinTrans":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetFinTrans requires 1 args")
      flag.Usage()
    }
    arg509 := flag.Arg(1)
    mbTrans510 := thrift.NewTMemoryBufferLen(len(arg509))
    defer mbTrans510.Close()
    _, err511 := mbTrans510.WriteString(arg509)
    if err511 != nil {
      Usage()
      return
    }
    factory512 := thrift.NewTJSONProtocolFactory()
    jsProt513 := factory512.GetProtocol(mbTrans510)
    argvalue0 := types.NewSearchCriteria()
    err514 := argvalue0.Read(context.Background(), jsProt513)
    if err514 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetFinTrans(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getDailyLedger":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDailyLedger requires 1 args")
      flag.Usage()
    }
    arg515 := flag.Arg(1)
    mbTrans516 := thrift.NewTMemoryBufferLen(len(arg515))
    defer mbTrans516.Close()
    _, err517 := mbTrans516.WriteString(arg515)
    if err517 != nil {
      Usage()
      return
    }
    factory518 := thrift.NewTJSONProtocolFactory()
    jsProt519 := factory518.GetProtocol(mbTrans516)
    argvalue0 := types.NewSearchCriteria()
    err520 := argvalue0.Read(context.Background(), jsProt519)
    if err520 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetDailyLedger(context.Background(), value0))
    fmt.Print("\n")
    break
  case "isPasswordChangeRequred":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IsPasswordChangeRequred requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IsPasswordChangeRequred(context.Background(), value0))
    fmt.Print("\n")
    break
  case "changePassword":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ChangePassword requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.ChangePassword(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getSettings":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetSettings requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetSettings(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getSetting":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetSetting requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetSetting(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "delSetting":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "DelSetting requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.DelSetting(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "saveSetting":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SaveSetting requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.SaveSetting(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "isUserRegistered":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IsUserRegistered requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IsUserRegistered(context.Background(), value0))
    fmt.Print("\n")
    break
  case "sendMail":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SendMail requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.SendMail(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "sendMailEx":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "SendMailEx requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    arg540 := flag.Arg(4)
    mbTrans541 := thrift.NewTMemoryBufferLen(len(arg540))
    defer mbTrans541.Close()
    _, err542 := mbTrans541.WriteString(arg540)
    if err542 != nil { 
      Usage()
      return
    }
    factory543 := thrift.NewTJSONProtocolFactory()
    jsProt544 := factory543.GetProtocol(mbTrans541)
    containerStruct3 := tradingservice.NewTradingServiceSendMailExArgs()
    err545 := containerStruct3.ReadField4(context.Background(), jsProt544)
    if err545 != nil {
      Usage()
      return
    }
    argvalue3 := containerStruct3.Attachments
    value3 := argvalue3
    fmt.Print(client.SendMailEx(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "registerAccount":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "RegisterAccount requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.RegisterAccount(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "requestWithdraw":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "RequestWithdraw requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2, err552 := (strconv.ParseFloat(flag.Arg(3), 64))
    if err552 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    fmt.Print(client.RequestWithdraw(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getAccountAttributes":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetAccountAttributes requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetAccountAttributes(context.Background(), value0))
    fmt.Print("\n")
    break
  case "delAccountAttribute":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "DelAccountAttribute requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.DelAccountAttribute(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getAccountAttribute":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetAccountAttribute requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.GetAccountAttribute(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "setAccountAttribute":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "SetAccountAttribute requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.SetAccountAttribute(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "setUser":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetUser requires 1 args")
      flag.Usage()
    }
    arg564 := flag.Arg(1)
    mbTrans565 := thrift.NewTMemoryBufferLen(len(arg564))
    defer mbTrans565.Close()
    _, err566 := mbTrans565.WriteString(arg564)
    if err566 != nil {
      Usage()
      return
    }
    factory567 := thrift.NewTJSONProtocolFactory()
    jsProt568 := factory567.GetProtocol(mbTrans565)
    argvalue0 := types.NewUser()
    err569 := argvalue0.Read(context.Background(), jsProt568)
    if err569 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetUser(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setQuote":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetQuote requires 1 args")
      flag.Usage()
    }
    arg570 := flag.Arg(1)
    mbTrans571 := thrift.NewTMemoryBufferLen(len(arg570))
    defer mbTrans571.Close()
    _, err572 := mbTrans571.WriteString(arg570)
    if err572 != nil {
      Usage()
      return
    }
    factory573 := thrift.NewTJSONProtocolFactory()
    jsProt574 := factory573.GetProtocol(mbTrans571)
    argvalue0 := types.NewQuote()
    err575 := argvalue0.Read(context.Background(), jsProt574)
    if err575 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetQuote(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setRating":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetRating requires 1 args")
      flag.Usage()
    }
    arg576 := flag.Arg(1)
    mbTrans577 := thrift.NewTMemoryBufferLen(len(arg576))
    defer mbTrans577.Close()
    _, err578 := mbTrans577.WriteString(arg576)
    if err578 != nil {
      Usage()
      return
    }
    factory579 := thrift.NewTJSONProtocolFactory()
    jsProt580 := factory579.GetProtocol(mbTrans577)
    argvalue0 := types.NewRating()
    err581 := argvalue0.Read(context.Background(), jsProt580)
    if err581 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetRating(context.Background(), value0))
    fmt.Print("\n")
    break
  case "delRating":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DelRating requires 1 args")
      flag.Usage()
    }
    arg582 := flag.Arg(1)
    mbTrans583 := thrift.NewTMemoryBufferLen(len(arg582))
    defer mbTrans583.Close()
    _, err584 := mbTrans583.WriteString(arg582)
    if err584 != nil {
      Usage()
      return
    }
    factory585 := thrift.NewTJSONProtocolFactory()
    jsProt586 := factory585.GetProtocol(mbTrans583)
    argvalue0 := types.NewRating()
    err587 := argvalue0.Read(context.Background(), jsProt586)
    if err587 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.DelRating(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setAccount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetAccount requires 1 args")
      flag.Usage()
    }
    arg588 := flag.Arg(1)
    mbTrans589 := thrift.NewTMemoryBufferLen(len(arg588))
    defer mbTrans589.Close()
    _, err590 := mbTrans589.WriteString(arg588)
    if err590 != nil {
      Usage()
      return
    }
    factory591 := thrift.NewTJSONProtocolFactory()
    jsProt592 := factory591.GetProtocol(mbTrans589)
    argvalue0 := types.NewAccount()
    err593 := argvalue0.Read(context.Background(), jsProt592)
    if err593 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetAccount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setSettlementPrice":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetSettlementPrice requires 1 args")
      flag.Usage()
    }
    arg594 := flag.Arg(1)
    mbTrans595 := thrift.NewTMemoryBufferLen(len(arg594))
    defer mbTrans595.Close()
    _, err596 := mbTrans595.WriteString(arg594)
    if err596 != nil {
      Usage()
      return
    }
    factory597 := thrift.NewTJSONProtocolFactory()
    jsProt598 := factory597.GetProtocol(mbTrans595)
    argvalue0 := types.NewSettlementPrice()
    err599 := argvalue0.Read(context.Background(), jsProt598)
    if err599 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetSettlementPrice(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setUserSession":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetUserSession requires 1 args")
      flag.Usage()
    }
    arg600 := flag.Arg(1)
    mbTrans601 := thrift.NewTMemoryBufferLen(len(arg600))
    defer mbTrans601.Close()
    _, err602 := mbTrans601.WriteString(arg600)
    if err602 != nil {
      Usage()
      return
    }
    factory603 := thrift.NewTJSONProtocolFactory()
    jsProt604 := factory603.GetProtocol(mbTrans601)
    argvalue0 := types.NewUserSession()
    err605 := argvalue0.Read(context.Background(), jsProt604)
    if err605 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetUserSession(context.Background(), value0))
    fmt.Print("\n")
    break
  case "archiveUserSession":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ArchiveUserSession requires 1 args")
      flag.Usage()
    }
    arg606 := flag.Arg(1)
    mbTrans607 := thrift.NewTMemoryBufferLen(len(arg606))
    defer mbTrans607.Close()
    _, err608 := mbTrans607.WriteString(arg606)
    if err608 != nil {
      Usage()
      return
    }
    factory609 := thrift.NewTJSONProtocolFactory()
    jsProt610 := factory609.GetProtocol(mbTrans607)
    argvalue0 := types.NewUserSession()
    err611 := argvalue0.Read(context.Background(), jsProt610)
    if err611 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.ArchiveUserSession(context.Background(), value0))
    fmt.Print("\n")
    break
  case "setAccountLimit":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SetAccountLimit requires 1 args")
      flag.Usage()
    }
    arg612 := flag.Arg(1)
    mbTrans613 := thrift.NewTMemoryBufferLen(len(arg612))
    defer mbTrans613.Close()
    _, err614 := mbTrans613.WriteString(arg612)
    if err614 != nil {
      Usage()
      return
    }
    factory615 := thrift.NewTJSONProtocolFactory()
    jsProt616 := factory615.GetProtocol(mbTrans613)
    argvalue0 := types.NewAccountLimit()
    err617 := argvalue0.Read(context.Background(), jsProt616)
    if err617 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SetAccountLimit(context.Background(), value0))
    fmt.Print("\n")
    break
  case "delAccountLimit":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "DelAccountLimit requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.DelAccountLimit(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
